services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://account-db:3306/accounts
      - SPRING_DATASOURCE_USERNAME=cavargas
      - SPRING_DATASOURCE_PASSWORD=cavargas
      - MS_CLIENT_URL=http://user-service:8080/api/clients
    networks:
      - devsu-microservices-network
  mysql:
    image: mysql:latest
    container_name: account-db
    environment:
      MYSQL_DATABASE: accounts
      MYSQL_USER: cavargas
      MYSQL_PASSWORD: cavargas
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devsu-microservices-network

networks:
  devsu-microservices-network:
    external: true
    name: my-shared-network